### PR TITLE
Additional fix for ignoring missing attributes

### PR DESCRIPTION
**Pull request by Alexwijn**
With the latest fix an error occur that it impossible to convert the empty (default) string to a valid time string. This pull request fixes that.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/sensor.py", line 250, in async_setup_entry
    await add_public_entities(False)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/sensor.py", line 220, in add_public_entities
    await data_handler.register_data_class(
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 181, in register_data_class
    await self.async_fetch_data(data_class_entry)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 139, in async_fetch_data
    await self.data[data_class_entry].async_update()
  File "/config/deps/lib/python3.9/site-packages/pyatmo/public_data.py", line 250, in async_update
    self.process(resp_data)
  File "/config/deps/lib/python3.9/site-packages/pyatmo/public_data.py", line 51, in process
    self.time_exec = to_time_string(resp.get("time_exec", ""))
  File "/config/deps/lib/python3.9/site-packages/pyatmo/helpers.py", line 29, in to_time_string
    return datetime.utcfromtimestamp(int(value)).isoformat(sep="_")
ValueError: invalid literal for int() with base 10: ''
````

### CODE REVIEW

**Comment by cgtobi** [comment]
Hi Alex,

thanks for investigating. I was actually considering to remove those variables completely as they are (at least in Home Assistant) not used.

**Comment by Alexwijn** [comment]
Yeah, I wanted to change as minimum as possible since I don't know the code base. But I'm running this locally with HA now just fine.

I was getting a bit annoyed that I did not had any weather info there (so a lot of automations were broken) for over a week now. So I decided to checkout your fix.

**Comment by cgtobi** [comment]
Yeah, if it wont get merged today I'll probably go ahead and push a release tomorrow. Thanks for checking out the fix. I didn't notice any issue, but good that you found them.

**Comment by cgtobi** [comment]
Thanks again for your contribution. I’ve removed the variables altogether.

**Pull request closed without merging**
